# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # Specifies the ecosystem (Node.js)
    directory: "/" # Location of package.json and package-lock.json
    schedule:
      interval: "weekly" # Run updates weekly
    ignore:
      - dependency-name: "prisma"
        versions: ["<4.0.0"] # Ignore old versions below 4.0.0
      - dependency-name: "@prisma/client"
        versions: ["<4.0.0"]
    groups:
      prisma-dependencies:
        patterns:
          - "prisma"
          - "@prisma/client"
      eslint-packages:
        patterns:
          - "eslint"
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
      nestjs-packages:
        patterns:
          - "@nestjs/testing"
          - "@nestjs/swagger"
          - "@nestjs/platform-express"
          - "@nestjs/common"
          - "@nestjs/core"
          - "@nestjs/axios"
    commit-message:
      prefix: "deps"
      include: "scope" # Adds the scope of the update (e.g., dependency name)
    open-pull-requests-limit: 10 # Prevent too many PRs at once
    rebase-strategy: "auto" # Automatically rebase if needed
    assignees:
      - "zamzami16" # Replace with a team or username
    labels:
      - "dependencies"
      - "dependabot"
    versioning-strategy: "increase" # Only update to newer versions

