name: Update Swagger UI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['22.x', '24.x']   # updated: removed 18 & 20, added 24
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # updated

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4   # updated
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'                # optional: cache node_modules

      - name: Install dependencies
        run: npm ci

      - name: Set up Prisma CLI
        run: npm install prisma --save-dev

      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test

      - name: Run integration tests
        run: npm test
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test
          PUBLIC_TOKEN: ba799c08-e47e-45f3-953e-81f66107dc73
          JWT_ACCESS_SECRET: f0f81d51-4e16-4fb7-b12f-ebf1a418c40c
          JWT_REFRESH_SECRET: 1XKuhizo3Xspwutej7gyfZeM8RgjY

  deploy-swagger:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # updated

      - name: Set up Node.js 22.x   # updated: use LTS instead of 18
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Swagger JSON
        run: npm run generate:swagger
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test
          PUBLIC_TOKEN: ba799c08-e47e-45f3-953e-81f66107dc73
          JWT_ACCESS_SECRET: f0f81d51-4e16-4fb7-b12f-ebf1a418c40c
          JWT_REFRESH_SECRET: 1XKuhizo3Xspwutej7gyfZeM8RgjY
          GENERATE_SWAGGER: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4   # updated to latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
