name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Set up Prisma CLI
        run: npm install prisma --save-dev

      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test

      - name: Run integration tests
        run: npm test
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test
          PUBLIC_TOKEN: ba799c08-e47e-45f3-953e-81f66107dc73
          JWT_ACCESS_SECRET: f0f81d51-4e16-4fb7-b12f-ebf1a418c40c
          JWT_REFRESH_SECRET: 1XKuhizo3Xspwutej7gyfZeM8RgjYrVFWE
